apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-processor
  namespace: keda-sample
  labels:
    app: amqp-processor
spec:
  selector:
    matchLabels:
      app: amqp-processor
  template:
    metadata:
      labels:
        app: amqp-processor
    spec:
      containers:
      - name: amqp-processor
        image: amqp-msg-processor:v001
        imagePullPolicy: IfNotPresent
        env:
        - name: AMQP_BROKER_HOST_PORT
          value: "artemis01:5672"
        - name: AMQP_ADDRESS
          value: "queue01"
        - name: AMQP_USER
          value: "user01"
        - name: AMQP_USER_PASSWORD
          value: "user01pw"
        envFrom:
        - secretRef:
            name: artemispasswd
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: amqp-processor
  namespace: keda-sample
  labels:
    deploymentName: amqp-processor
spec:
  scaleTargetRef:
    deploymentName: amqp-processor
  triggers:
  - type: activemq-artemis
    metadata:
      queueName: queue01
      jolokiaHost: 'https://admin01:@artemis01.keda-sample.svc.cluster.local:8161'
      queueLength  : '5'
      passwordKey  : ARTEMIS_J_PASSWORD
      trustCA: |
        -----BEGIN CERTIFICATE-----
        MIIEBzCCAu+gAwIBAgIUFsKFI79AcElN1GTW5MmTMjiyyJ8wDQYJKoZIhvcNAQEL
        BQAwgZIxCzAJBgNVBAYTAlhYMRAwDgYDVQQIDAdEZWZhdWx0MRUwEwYDVQQHDAxE
        ZWZhdWx0IENpdHkxFDASBgNVBAoMC1NlbGYgU2lnbmVkMRIwEAYDVQQLDAlNZXNz
        YWdpbmcxMDAuBgNVBAMMJ2FydGVtaXMwMS5rZWRhLXNhbXBsZS5zdmMuY2x1c3Rl
        ci5sb2NhbDAeFw0xOTA5MjExNTEyMzJaFw0yOTA5MTgxNTEyMzJaMIGSMQswCQYD
        VQQGEwJYWDEQMA4GA1UECAwHRGVmYXVsdDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5
        MRQwEgYDVQQKDAtTZWxmIFNpZ25lZDESMBAGA1UECwwJTWVzc2FnaW5nMTAwLgYD
        VQQDDCdhcnRlbWlzMDEua2VkYS1zYW1wbGUuc3ZjLmNsdXN0ZXIubG9jYWwwggEi
        MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpUMj+KHVFilgxiNyWUr7tdcQP
        xcF41oxKenLnHNbQIflMsaiNt2SvmQd3G0Y50KH4GLCipekVZkPp61E2K2uoGcYA
        gaFN78VwihRE6Wk3rJcTu+xsQiRYVqCG5WAY4pjq5TqqgULDDlFzECCVIwdXrPEE
        oudnG7g4w6MdMeWsWqS7jYm2O/1gHlKoSRCu+QLo3sHG0enxScib8meZDb/oAxr5
        1hh0cWBS8c/f5Fku+Q6gu4WMOnCeqDsaTagfnW+ayu3iyHqPJWFMPVHlLt/RfEk7
        tKHfldS5T5NZJw+8wUD1UqxPQs6EfCRAnTcAzrc4/5kxTJIYVSptiWgS/CqfAgMB
        AAGjUzBRMB0GA1UdDgQWBBRX7NlURYype/OkrRnJJHgqgWkOeDAfBgNVHSMEGDAW
        gBRX7NlURYype/OkrRnJJHgqgWkOeDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
        DQEBCwUAA4IBAQBXGZwQKXUOLPSVYD/bqG3ZhiOKJWHp4u/TWpf18OxxHIUiKCXS
        JZue1DZ6actkha19zXRQF+Ed7D3bhVQXKsq4M4JZtM6P+ZLlEn6Rq2QCl+66K3Z+
        e7fB8Whib/vasccmtd4XmMOipp5BZVLHQS0gFUJnolnJVWKd95BLt7xRDFMgAZe2
        Rm2l864UOAThg+0ghdJ8hQIMbsynQH1NfSu6hs3ScH+K1VI895Dby3d9o+TcKVt+
        OmD76cXSQWW4GM91L7nFsJmY7TBXNGwI7gaPbTjr8U9hPp0Ze+EfzemiiEWBMXY2
        cOooGeC525EvI4MLjuw1n6A5UxvwXm8xLufB
        -----END CERTIFICATE-----
---
